### ISSUE TITLE
Cannot install on Debian Jessie

### ISSUE THREAD

**Issue by moa3** [hsanson/chrome-pass#1]
`
 $ pip3 install --user chrome-pass==0.1.5
Downloading/unpacking chrome-pass==0.1.5
  Downloading chrome-pass-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-31m2b2z9/chrome-pass/setup.py) egg_info for package chrome-pass

Downloading/unpacking python-gnupg (from chrome-pass==0.1.5)
  Downloading python_gnupg-0.3.9-py2.py3-none-any.whl
Installing collected packages: chrome-pass, python-gnupg
  Running setup.py install for chrome-pass
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

```
error: option --single-version-externally-managed not recognized
Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-31m2b2z9/chrome-pass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ats18pn2-record/install-record.txt --single-version-externally-managed --compile --user:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
```

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help

error: option --single-version-externally-managed not recognized
`

From Logs:

`
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-31m2b2z9/chrome-pass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ats18pn2-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-31m2b2z9/chrome-pass
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-31m2b2z9/chrome-pass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ats18pn2-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-31m2b2z9/chrome-pass
`

**Comment by moa3** [comment]
Fixed it by doing 
`pip3 install --egg --user chrome-pass==0.1.5`

**Comment by hsanson** [comment]
Good to hear you got it solved. Seems the problem is caused by an old version of setuptools. Some other options to fix this are to upgrade setuptools:

  http://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind
