### ISSUE TITLE
pgp-agent not found

### ISSUE THREAD

**Issue by BishopT** [hsanson/chrome-pass#12]
In order to workaround the issues #8 and #9, I've set GnuPG 1.4 so it knows my secret key. chrome-pass extension still fails since it can't contact gpg-agent : 
`gpg: gpg-agent is not available in this session`
`gpg: Sorry, no terminal at all requested - can't get input`

First, it was true that gpg-agent was not found by gpg 1.4 ; the command `nativePass pass something` was giving the same output. Then I managed to create the old GPG_AGENT_INFO env variable so that gpg 1.4 now find the agent and nativePass in terminal now prints out decrypted passwords.

But the extension is still stuck in the same state.

**Comment by hsanson** [comment]
I am unable to provide help on this kind of issues. But let me try to provide pointers that may help you solve it.

Unfortunately in linux is difficult to know if the nativePass program is being executed with the correct environment when invoked from chrome. You mention that you set the GPG_AGENT_INFO env variable to get it to work.

I assume you created that env variable in a terminal and executed the nativePass command in that same terminal. Can you try running the nativePass command on a different terminal window and see if it still works without setting the GPG_AGENT_INFO?

If it does not work it means that the GPG_AGENT_INFO is present only within the scope of the previous terminal. If you want this to work in Chrome you must ensure that this variable, or better said, you must ensure that gpg-agent is correctly configured in a context available to Chrome. This usually means that gpg-agent env variables must be set by the X window process or the DE (Gnome/Kde/Xfce/whatever) process.

You may try to force the env variables within the nativePass script by setting them, in python, at the beginning of the script. This of course is not flexible as it will be overwritten every time you upgrade.

Also in the readme there are additional things you may try to verify:

  1. Check the location of the nativePass manifest is correct.
  2. Ensure the manifest extension id matches the one in the chrome plugin.
  3. Ensure the manifest is pointing to the nativePass location you now works in terminal.

**Comment by BishopT** [comment]
Hi there!

Thanks for the hint. I just put the commands in the .profile file (in
Ubuntu based distro) instead of .bashrc

Works like a charm now...


Le 26 sept. 2017 01:57, "Horacio Sanson" <notifications@github.com> a
écrit :
