### ISSUE TITLE
Some forms reject filled in content because no key was pressed

### ISSUE THREAD

**Issue by kinnison** [hsanson/chrome-pass#14]
Several login forms refuse to accept the user/pass entered by chrome-pass because they're hooking the input events to decide if anything has even been put in.

For example, netflix.com  and plex.tv

Currently I get around this by clicking in the fields and pressing a key and then backspace in order to trick the form into believing I entered the data by hand.

I'm afraid that I can't quite identify how/why this happens and thus how to fix it in terms of events to send.

**Comment by hsanson** [comment]
These services disable password copy/pasting on purpose:

 - https://support.mozilla.org/ja/questions/916528
 - https://digiwonk.gadgethacks.com/how-to/re-enable-copy-paste-annoying-sites-block-0155910/
 - https://www.reddit.com/r/daydream/comments/5j7l33/is_there_some_trick_to_entering_netflix_password/

It is supposed to be a security feature, but as many have pointed out it offers little, if not any, security benefits at the cost of user usability.

I don't think is worth the effort to bypass this by modifying the javascript on those pages and possibly breaking the user policy of those services.
