### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by ghost** [hsanson/chrome-pass#2]
I had to change your nativePass python script to be able to use it with chromium.

`nativePath = os.environ['HOME'] + "/.config/chromium/NativeMessagingHosts/"`

As described here: https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-location

Few points/tips:
- Your python script; 2 spaces and sometimes 4? Stick to the 4 spaces as everybody does.
- It's not very clear that you need your python script to be able to use your extension. I just installed the extension and it wasn't working.

**Comment by hsanson** [comment]
Thanks for the tips. I have addressed them as best I could.
