### ISSUE TITLE
Extension unavailable

### ISSUE THREAD

**Issue by notorand-it** [hsanson/chrome-pass#35]
The extension is not available any more on chromewebstore:
See [here](https://chromewebstore.google.com/detail/chrome-pass-zx2c4/oblajhnjmknenodebpekmkliopipoolo).

![SHOT-20240309-1228 ss](https://github.com/hsanson/chrome-pass/assets/5338874/07ca6fe0-0358-4414-b320-93446d37edec)

**Comment by hsanson** [comment]
Works find from what I can see. Checked the developer console and there are no visible issues, the plugin appears published, and is distributed on all regions. Maybe check the `Visualizza la guida` to see if there is more details on what the problem may be.

![image](https://github.com/hsanson/chrome-pass/assets/900716/cbf147a6-e6bf-49c6-9e77-90b8c2f098f8)
