### ISSUE TITLE
Fill in password only

### ISSUE THREAD

**Issue by naleo** [hsanson/chrome-pass#5]
Would it be possible to create an option to fill in password only?

**Comment by hsanson** [comment]
Can you provide a page with a login form that would require that option?

Currently if there is a single password input box (Google/Gmail) in the page it will be filled with the password.

**Comment by naleo** [comment]
What I am saying is that I have stored my password with the username as the second line of the file, and the filename is the website which I am at, so whenever I use your extension to fill in a password, it puts the websites name in the username field

**Comment by hsanson** [comment]
Sorry but this use case deviates from the way I use this plugin. Feel free to fork and modify it to your use pattern. The code is very simple to understand but if you have any troubles I would be more than happy to help.
