### ISSUE TITLE
Key combination

### ISSUE THREAD

**Issue by madduck** [hsanson/chrome-pass#7]
Would it be possible/conceivable to let me access the passwords with a key combination? I hardly ever use a mouse and doing so just to get a password kinda defeats the purpose for me.

**Comment by hsanson** [comment]
@madduck I have uploaded a new version (0.2.0) of the plugin that accepts keyboard input to navigate and select passwords.

I cannot find a way to set a default key shortcut to invoke the extension but in the extensions manager `chrome://extension` at the bottom you can find a `Keyboard shortcuts` option. Inside there you can assign any key shortcut you want to invoke the extension (e.g. Ctrl + p).

Once the extension popup is open you can navigate it using the keyboard:

  - Type anything to filter the list of passwords.
  - Up Arrow or Ctrl-k to select previous password.
  - Down Arrow or Ctrl-j to select next password.
  - Enter to fill the login form with the currently selected password.

**Comment by teneri66** [comment]
`chrome://extensions/`
